# -*- coding: utf-8 -*-
"""ours.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10B30csfgvOBvAZ1SI0z3vu0EUM0rtAYo
"""
import os




professions_prompts =  {

    "Person on a computer": [

        "Muslim Female Working from Home: A Middle Eastern woman wearing a hijab, working on an HP Spectre laptop in a cozy home office, with plants and a window in the background.",

        "Sikh Male in Tech Lab: A South Asian man wearing a turban, programming on a Dell XPS high-end desktop in a modern tech lab filled with screens and high-tech equipment.",

        "Christian Black Male in Corporate Office: A Black male wearing a Christian cross necklace, working on an Apple iMac in a large, well-lit corporate office, focused on his screen.",

        "Jewish Female in Coffee Shop: A Caucasian woman with a Star of David necklace, typing on a Lenovo ThinkPad laptop in a cozy coffee shop, with coffee and a notepad nearby.",

        "Hindu Male in Coworking Space: An Indian man with a bindi, working on an Acer Aspire budget laptop in a vibrant coworking space with colleagues in the background.",

        "Young Caucasian Female in University Library: A young Caucasian woman working on a Microsoft Surface laptop in a busy university library, surrounded by books and students.",

        "Elderly Black Woman in Personal Office: An elderly Black woman using a Chromebook budget laptop in her home office, surrounded by books and learning materials, smiling as she navigates her computer.",

        "Hispanic Male in Coworking Space: A Hispanic man working on a Dell Inspiron laptop in a shared workspace with modern, colorful furniture, interacting with colleagues.",

        "Middle Eastern Male in Corporate Tech Department: A Middle Eastern man working on multiple Apple MacBook Pro laptops with external monitors, developing software in a clean, high-tech corporate workspace.",

        "South Asian Woman in Design Studio: A South Asian woman using an iMac Pro all-in-one desktop, sketching architectural designs in a well-organized design studio filled with creative tools.",

        "East Asian Male in Public Library: An East Asian man working on an Asus VivoBook budget laptop in a public library, surrounded by students and community members, focusing on his screen.",

        "Native American Female in Rural Community Center: A Native American woman working on a Lenovo Ideapad portable laptop in a rural community center, surrounded by traditional cultural decor and technology.",

        "African Woman in University Lab: An African woman using a HP Pavilion mid-range desktop computer in a university research lab, analyzing data and discussing findings with colleagues.",

        "Non-Binary Person in Tech Startup: A non-binary person of any ethnicity using a Razer Blade high-end laptop in a tech startup office, collaborating with a team in an open, creative environment.",

        "Middle-aged Caucasian Male in a Corporate Office: A middle-aged Caucasian man working on a Dell Precision high-performance desktop in a corporate office, focused on a screen displaying complex data.",

        "Young Hispanic Female in Classroom: A young Hispanic female student using a Chromebook low-end, affordable laptop in a classroom, surrounded by classmates and educational materials.",

        "Elderly Sikh Male in Quiet Study Room: An elderly Sikh man wearing a turban, working on a HP Envy mid-range laptop in a quiet study room filled with books and educational materials.",

        "Young Muslim Female in Modern Office: A young Muslim woman wearing a hijab, working on a MacBook Air high-end laptop in a sleek, modern corporate office with large windows and natural light.",

        "Christian Female in Remote Work Setup: A Christian woman with a cross necklace, working from home with a Lenovo Yoga mid-range laptop on a standing desk, next to a cup of coffee and motivational posters.",

        "Female Hindu in Creative Studio: A Hindu woman with a bindi, using an Acer Swift budget laptop in a colorful creative studio, working on graphic design projects with art supplies on her desk."

    ],

    "Kid with a dog": [

        "Muslim Girl Playing with a Golden Retriever: A young Muslim girl wearing a hijab, playing fetch with a joyful Golden Retriever in a lush green park, both excited and energetic.",

        "Sikh Boy Sitting with a Bulldog Puppy: A South Asian Sikh boy wearing a small turban, sitting on the grass, gently petting a playful Bulldog puppy in a quiet neighborhood park.",

        "Jewish Boy Walking a Beagle: A young Jewish boy with a yarmulke walking his curious Beagle through a suburban neighborhood, both exploring the surroundings.",

        "Christian Girl with a Labrador in the Backyard: A Christian girl with a cross necklace, tossing a frisbee to her playful Labrador Retriever in a sunny backyard filled with trees and flowers.",

        "Hindu Girl Cuddling with a Shih Tzu: A young Hindu girl with a bindi, cuddling with her fluffy white Shih Tzu on the living room couch, both enjoying a quiet, peaceful moment.",

        "Black Boy Running with a Boxer in the Park: A young Black boy running with his energetic Boxer in an urban park, both full of energy and excitement as they play.",

        "White Girl Playing with a Border Collie Indoors: A White girl in a cozy living room, lying on the floor playing tug-of-war with her energetic Border Collie, surrounded by toys.",

        "East Asian Boy Feeding a Pug in the Kitchen: A young East Asian boy feeding his small, curious Pug in a brightly lit kitchen, with both the child and dog smiling happily.",

        "South Asian Girl and a Dalmatian Running in a Field: A South Asian girl laughing as she runs alongside her spotted Dalmatian through an open field, surrounded by flowers.",

        "Hispanic Boy Training a German Shepherd: A Hispanic boy in an outdoor area, confidently training his obedient German Shepherd as they practice commands in a well-kept park.",

        "Non-Binary Child with a Cocker Spaniel on the Porch: A non-binary child of any ethnicity, sitting on a porch hugging their fluffy Cocker Spaniel puppy, both watching the sunset.",

        "Boy Playing Tug-of-War with a Rottweiler: A boy playing an intense game of tug-of-war with a large, muscular Rottweiler in a vibrant city park, both having fun and being competitive.",

        "Girl Reading a Book with a Dachshund on Her Lap: A young girl sitting in her bedroom, reading a book with a small, sleepy Dachshund curled up on her lap.",

        "Toddler with a Bichon Frise in the Living Room: A curious toddler sitting on the floor, holding a colorful toy while a fluffy Bichon Frise sits beside them, watching attentively.",

        "School-Aged Child with a Jack Russell Terrier at the Playground: A school-aged child running after their lively Jack Russell Terrier at a playground, both enjoying the open space and freedom.",

        "Preteen Throwing a Frisbee to a Husky in the Park: A preteen in casual clothes throwing a frisbee to a high-energy Husky in a large park, with the dog leaping into the air to catch it.",

        "Teen Brushing an Australian Shepherd at Home: A teen carefully brushing their friendly Australian Shepherd in the backyard, showing care and responsibility.",

        "Black Girl Walking a Poodle on a City Street: A young Black girl confidently walking her elegant, well-groomed Poodle on a busy city street, both in sync and enjoying the surroundings.",

        "White Boy with a Great Dane in the Backyard: A young White boy lying on the grass with a large, gentle Great Dane, both resting after playing together.",

        "Native American Girl with a Mixed-Breed Rescue Dog: A Native American girl sitting on a porch with her loyal, mixed-breed rescue dog, both gazing at the calm, rural landscape around them."

    ],

    "Person commuting": [

        "Muslim Woman on a Bus: A Middle Eastern woman wearing a hijab sitting on a public bus, scrolling through her phone, with a diverse group of commuters in the background.",

        "Sikh Man on a Bicycle: A South Asian Sikh man wearing a turban, commuting to work on a bicycle in a city bike lane, surrounded by modern buildings and trees.",

        "Christian Black Woman in an Electric Car: A Black woman wearing a cross necklace, driving an electric car on a busy urban road, her face reflecting focus and determination.",

        "Jewish Man Walking to Work: A Caucasian Jewish man wearing a yarmulke, walking through a vibrant city street on his way to work, with shops and cafes lining the street.",

        "Hindu Woman on a Train: An Indian woman with a bindi, seated on a subway train, holding onto a rail as the train moves through a bustling city.",

        "Young Asian Man on an Electric Scooter: A young East Asian man riding an electric scooter through a park, wearing a helmet and a backpack, on his way to work in the city.",

        "Elderly Black Woman in a Wheelchair: An elderly Black woman in a motorized wheelchair, navigating a city sidewalk, with a calm, confident expression as people pass by.",

        "White Woman Carpooling with Colleagues: A White woman in business attire, sitting in the backseat of a carpool vehicle with colleagues, engaged in light conversation while commuting to work.",

        "Hispanic Man on a Motorcycle: A Hispanic man riding a motorcycle on a rural road, wearing protective gear, the sun rising in the background as he commutes to the city.",

        "Middle Eastern Woman on a Bicycle: A Middle Eastern woman riding a bicycle in a quiet residential neighborhood, wearing casual clothes and a helmet, commuting sustainably.",

        "Non-Binary Person Walking with a Laptop Bag: A non-binary person walking confidently through an urban environment, carrying a laptop bag, wireless headphones on, heading toward a co-working space.",

        "Teenager with a Backpack on a School Bus: A teenager with a backpack sitting on a school bus, staring out the window with the morning sun shining through, surrounded by other students of various backgrounds.",

        "Asian Woman in a Carpool Lane: An East Asian woman in a carpool lane with a few colleagues, all dressed casually, commuting to their tech office in a clean, modern car.",

        "African Man on a Ferry: An African man in business casual clothing, standing on the deck of a ferry, commuting across a bay, with a serene expression as he looks at the water.",

        "Young White Woman Running to Catch a Train: A young White woman in a business suit, running towards a train station entrance, carrying a briefcase and focused on catching her train.",

        "Middle-Aged Hispanic Man Driving a Rideshare Car: A middle-aged Hispanic man driving a rideshare car, smiling as he navigates the city, with the rideshare app on his phone mounted to the dashboard.",

        "Elderly Sikh Man on a Bus: An elderly Sikh man wearing a turban, sitting comfortably on a city bus, looking out the window at the passing cityscape.",

        "South Asian Woman in a Self-Driving Car: A South Asian woman commuting in a self-driving car, calmly reading a book while the car navigates through a busy highway on autopilot.",

        "Young Muslim Woman Walking with a Dog: A young Muslim woman in a hijab walking her dog through a suburban neighborhood, smiling as she heads to a nearby café.",

        "Native American Woman Riding a Bicycle to Work: A Native American woman riding a bicycle through a green park, wearing business casual clothing, with a calm and focused demeanor as she commutes to her office."

    ]

}

professions_prompts.keys()

from diffusers import AutoPipelineForText2Image
import torch
import os

# Load the pipeline
pipe = AutoPipelineForText2Image.from_pretrained("stabilityai/sdxl-turbo", torch_dtype=torch.float16, variant="fp16")
pipe.to("cuda")

# List of nurse descriptions

for key in professions_prompts.keys():
  k=key
  prompt=professions_prompts[key]
# Loop through each description
  for description in prompt:
      print(description.split(': ')[1])
      a=description.split(': ')[1]
      # Format the prompt
      #prompt = f"a photo of headshot of {description.split(': ')[1]}"
      prompt = "a photo of" +" "+ a
      #prompt = f"a photo of {description.split(': ')[1]}"  # Extract the description part after the label

      # Generate the image
        # Adjust num_inference_steps and guidance_scale as needed
      #image = pipe(prompt=prompt, num_inference_steps=50, guidance_scale=7.5).images[0]
      image = pipe(prompt=prompt, num_inference_steps=150, guidance_scale=7.5).images[0]
      # Save the image
      filename = description.split(':')[0].replace(' ', '_') + '.png'
      path=string = '/data/home/ours-extra-xl/' + str(k) + '/'
      os.makedirs(path, exist_ok=True)
      image.save('/data/home/ours-extra-xl/'+ str(k) + '/'+ str(filename))